### ISSUE TITLE
Programmatic access to exemplar_chars without dropping index chars

### ISSUE THREAD

**Issue by kontur** [googlefonts/lang#138]
For a given language textproto with `exemplar_chars` containing `index` like [e.g. Asturian](https://github.com/googlefonts/lang/blob/77b554d29e4ac31e57b1d662e01566ff193ddf93/Lib/gflanguages/data/languages/ast_Latn.textproto#L8):

```
exemplar_chars {
  base: "A Á B C D E É F G H Ḥ I Í L Ḷ M N Ñ O Ó P Q R S T U Ú Ü V X Y Z a á b c d e é f g h ḥ i í l ḷ m n ñ o ó p q r s t u ú ü v x y z"
  auxiliary: "À Ă Â Å Ä Ã Ā Æ Ç È Ĕ Ê Ë Ē Ì Ĭ Î Ï Ī J K Ò Ŏ Ô Ö Ø Ō Œ Ù Ŭ Û Ū W Ÿ ª à ă â å ä ã ā æ ç è ĕ ê ë ē ì ĭ î ï ī j k º ò ŏ ô ö ø ō œ ù ŭ û ū w ÿ"
  marks: "◌́ ◌̃ ◌̈ ◌̣"
  numerals: "- , . % + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- – — , ; : ! ¡ ? ¿ . … \' ‘ ’ \" “ ” « » ( ) [ ] @ * / \\ & #"
  index: "A B C D E F G H I L M N Ñ O P Q R S T U V X Y Z"
}
```

…the python interface will return `base` / `auxiliary` with subtracted `index` chars and any components thereof, so e.g.:

```
from gflanguages import LoadLanguages()
LoadLanguages()["ast_Latn"].exemplar_chars.base
> 'a á b c d e é f g h ḥ i í l ḷ m n ñ o ó p q r s t u ú ü v x y z'
```

I'd expect the return to be: `'A Á B C D E É F G H Ḥ I Í L Ḷ M N Ñ O Ó P Q R S T U Ú Ü V X Y Z a á b c d e é f g h ḥ i í l ḷ m n ñ o ó p q r s t u ú ü v x y z'`

The return without the `index` characters / capitals is unexpected when other languages without the `index` will return upper and lower case combined, e.g.

```
LoadLanguages()["arn_Latn"].exemplar_chars.base
> 'A B C D E F G I J K L M N O P Q R S T U W X Y Z Ü Ñ a b c d e f g i j k l m n o p q r s t u w x y z ü ñ'
```

Is this intentional? And how can you get the full `base` without the magic removal of `index` characters and composites?

**Comment by moyogo** [comment]
It looks like the version of gflanguages you're running code with is older than the one with which you're checking data. Uppercase were added to bicameral language orthographies a while ago. Gflanguages returns the raw exemplar string, the latest version will give you a strong with all the letters uppercase and lowercase.

**Comment by kontur** [comment]
Woopsie, my bad. Not sure why, but when I yesterday pip installed gflanguages without specific version it pulled a very outdated one.
