### ISSUE TITLE
Establish gflanguages->gfglyphsets update notification command chain

### ISSUE THREAD

**Issue by yanone** [googlefonts/lang#148]
Ideally, I'd like to see this automated, but I'm not sure how.
And it's also not a big deal currently, but I want to establish this for the future. It will surely get more critical at some point down the road.

Here's the problem: I hadn't noticed (as the `gfglyphsets` maintainer) that three African languages were added to `gflanguages` about three months ago. Their existence remained unnoticed until `v0.6.0` was published two days ago for different reasons.

Thankfully, those three languages didn’t add any characters to the GF_Latin_African glyphset, but did indeed add character sequences which should have been checked as part of `fontbakery`'s `shape_languages` check in the meantime.

Currently I see no other way of dealing with this than to regularly rerun `gfglyphset`'s build command using a repository clone of `gflanguages` to see if any glyphset definitions are impacted by changes in `gflanguages`.

Ideally, such a method would somehow be incorporated into `gflanguages`'s own CI, which would somehow flag that a `gflanguages` release is needed, which would automatically trigger a dependency update in both `gfglyphsets` as well as `fontbakery`.

Unless anyone has better ideas, I would like to base this flag on whether or not glyphset definitions change as a result of changes in `gflanguages`. But I don't know yet how to implement this. I'm thinking some kind of regression check that compares the contents of `gfglyphsets`'s `/data` folder before and after the changes.

For now, I'd like to ask @simoncozens and/or @moyogo and/or whoever authors language data changes, to consider releasing a `gflanguages` update afterwards.

**Comment by simoncozens** [comment]
> which would automatically trigger a dependency update in both gfglyphsets as well as fontbakery.

Sure we should do this the other way around? ie if gfglyphsets and fontbakery have renovate set up (fontbakery does), then they will automatically be notified about new releases of gflanguages.

**Comment by yanone** [comment]
The renovate dependency update was implied in the quoted sentence. This works already.

The problem is that a gflanguages update wasn't released until three months after language changes were made.

I'm currently developing a GH action for glyphsets that checks for changes. Will report back how it goes.

**Comment by moyogo** [comment]
Isn't the solution to either wait for the gflanguages release or release a new gflanguages. I guess glyphsets can have a test set on the latest main branch commit if you want to test that.

**Comment by yanone** [comment]
> Isn't the solution to either wait for the gflanguages release or release a new gflanguages.

Yes. That's exactly my point. Nobody made a release in three months, and nobody noticed either. So we waited and nothing happened ;)

I just finished this action for glyphsets:

[This action](https://github.com/googlefonts/glyphsets/blob/main/.github/workflows/checklang.yml) will create such an [issue](https://github.com/googlefonts/glyphsets/issues/192) (tested with a `lang` fork).

**Comment by moyogo** [comment]
@yanone nobody is maintaining gflanguages. What do you expect?

**Comment by yanone** [comment]
Simon officially maintains it.

Apart from that, I'm not expecting anything. That's why I just worked out a solution so that I get notified even if nobody else reacts.

I think that's fair, and I haven't blamed anyone for not reacting on time. I found out about the data changes by accident and found a solution.

**Comment by simoncozens** [comment]
In general I merge PRs and then make a release. The commits might have been old, but they only got added to main this week. I'm not sure what you mean by "no-one noticed'?

**Comment by yanone** [comment]
> I'm not sure what you mean by "no-one noticed'?

The last release before 0.6.0 was three months ago on February 2nd. Three days later, on February 5th Denis added some African language definitions that should have been included in glyphsets. But I only have the renovate bot that notifies me of gflanguages package updates; I don't manually observe gflanguages commit history every other day. So I didn't notice that we were missing a release, and no one else noticed either and made one.

Within the gflanguages repository, there must be an information chain that reliably results in a release when necessary. That language data needs to travel downstream quickly – we’re live in production with all our tools and data.

With the GH action, today I closed the information gap, so that at least I can react when necessary.

One person must exist per repository that must be notified to cut a release after important data was added or changed. In my opinion, that's the person that's listed in the Pipeline Infrastructure Repository Maintainers doc.

**Comment by yanone** [comment]
Sorry, my apologies for the repeated use of the word "must". I should have written "should". I'm just trying to solve this problem that will certainly present itself again in the future if left unaddressed.

**Comment by simoncozens** [comment]
> Three days later, on February 5th Denis added some African language definitions that should have been included in glyphsets.

No, he didn't. He made a PR to add them. They weren't added until this week.

**Comment by yanone** [comment]
Ah, I see. I looked at the commit history where the commits where dated February 3rd, and overlooked that a PR was merged a month ago on April 2nd which included those commits. The relation wasn't apparent on the commit page itself. I apologize for having misinterpreted the data.

Slight change in topic: I expanded my work on the scheduled diff generator from yesterday into a new action that runs the glyphset assembler on every PR push, see [this test PR](https://github.com/googlefonts/glyphsets/pull/201) and look for commits titled [Update glyphset data](https://github.com/googlefonts/glyphsets/pull/201/commits/e82ec0cf97dd5aed5a6672d993daf6cbadaa0c6a)

With it, it's theoretically possible to change just the glyphset definitions (like adding or removing a language code), and the action will update the actual glyphset data files automatically by adding another commit to the PR.

The same will go for `gflanguages` release updates as delivered by renovate bot PRs: As soon as a new `gflanguages` version affects glyphset data, the changed data will automatically become part of the PR, so it's immediately visible whether a new `glyphsets` release is required. 

There's a slightly dodgy part, though: I had to generate a GH Public Access Token and add it to the repo secrets and use it in the action, because otherwise the workflow runs won't be repeated on the automatically added commits. This is to prevent endless workflow run loops. 
Since the token is personal, I hope this works for other people making PRs.

If one of you feels like testing this, please make a test PR to `glyphsets` by adjusting any glyphsets definition in `/Lib/glyphsets/definitions` and see whether the glyphset data changes itself.
Let me know if anything looks weird about the [action](https://github.com/googlefonts/glyphsets/blob/main/.github/workflows/update_pr.yml). I'm very new to this.
