### ISSUE TITLE
semantic issue in Ukrainian sample text

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/lang#155]
https://github.com/googlefonts/lang/blob/136e32b1982ed8cfe3605de97ccbdd095b93b3a9/Lib/gflanguages/data/languages/uk_Cyrl.textproto#L23

should be:
` styles: "Беручи до уваги, що визнання гідності"`

`,яка` (=_that_) is unnecessary and misleading in a heading

**Comment by alexeiva** [comment]
https://github.com/googlefonts/lang/blob/136e32b1982ed8cfe3605de97ccbdd095b93b3a9/Lib/gflanguages/data/languages/uk_Cyrl.textproto#L21

These glyphs would be more characteristic of Ukrainian:

```
  masthead_full: "ҐґЄє"
  masthead_partial: "Її"
```

**Comment by davelab6** [comment]
Excellent! Thank you @alexeiva :) 

cc @evanwadams @nathan-williams @twardoch @simoncozens @chrissimpkins
