### ISSUE TITLE
Set up Kirat Rai script

### ISSUE THREAD

**Issue by emmamarichal** [googlefonts/lang#180]
"The `Kirat Rai` script is used to write the `Bantawa` language in the Sikkim state of India."
The tag seems to be: `krai`

We need it for that font: https://github.com/google/fonts/pull/8431

- [ ] sample text
- [x] subset
- [x] primary script

cc @simoncozens

**Comment by simoncozens** [comment]
Subset was added in: https://github.com/googlefonts/nam-files/pull/21 @garretrieger please confirm the new U16 subsets are wired up with the server and ready to be used.

We actually have Bantawa sample text in `bap_Deva`. Presumably this can be transliterated.

I'll add script entries for all the U16 scripts.

**Comment by garretrieger** [comment]
Confirmed the Kirat Rai subset definitions have been onboarded and are present in all of our services.

**Comment by simoncozens** [comment]
Thank you! So all that's left is for me to transliterate the sample text and do another lang release.
