### ISSUE TITLE
Add "source" metadata field

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/lang#26]
Adding the Tangsa sample text in #25 reminded me that, at some point, someone's going to look at that and think "What is that text? Where did we get it from? Is it the UHDR or is it something else? Where do we report bugs in it?" And they might find the commit log and *possibly* trace it back to the PR (although I didn't put any notes in the commit log, just in the PR body), but it would be more robust if we could annotate the textproto files themselves with this kind of source information.

I suppose if we don't really need it as a field, we could just add comments.

**Comment by moyogo** [comment]
We can have `repeated string source` and `optional string note` for both language and sample_text.
I’m not sure it would be useful to have more specific fields like `masthead_source`, `poster_source`, `specimen_source`.

**Comment by simoncozens** [comment]
I think it's probably easier just to add comments.
