### ISSUE TITLE
Yoruba sample text issue (or glyphset issue?)

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/lang#30]
@moyogo inspecting the changes of #16 in sandbox, some glyphs are still falling back to another fonts

<img width="1430" alt="Capture d’écran 2022-10-26 à 15 37 34" src="https://user-images.githubusercontent.com/12222436/198041582-cbfa34ca-fb89-4fac-97f8-7e02fce93889.png">

I don't remember if this is this kind of issue:
`o dotbelow _ acutecomb` instead of `o acute _ dotbelowcomb` (but I don't think it should change anything in term of text composition)

Or if it is because the comb accents are missing from the Latin .nam glyphset.

**Comment by jvgaultney** [comment]
This remains a major issue with all our Latin fonts, and there seems to have been no progress since October. See https://github.com/google/fonts/issues/5385
