### ISSUE TITLE
Issue with Tai Viet and Lepcha

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/lang#31]
- [x] Tai Dam (Tai Viet script) doesn't appear in Asian languages in [Tai Heritage Pro](https://fonts.google.com/specimen/Tai+Heritage+Pro) specimen page, and primary script doesn't work for Tai Viet.
- [x] Same pour Sanskrit Lepcha in [Mingzat](https://fonts.google.com/specimen/Mingzat)

The 2 scripts are not listed in the "language" roll down menu, so I guess it is connected. Could we add the language tags into metadata.pb for these 2 fonts?

cc @nathan-williams @chrissimpkins @garretrieger

**Comment by vv-monsalve** [comment]
From the experience of Chinese Noto sources, two conditions had to be met:

1. Include the "languages" in the metadata (google/fonts/[#4722](https://github.com/google/fonts/pull/4722/files))
2. Add a particular region to some language `.textproto` files (googlefonts/lang[/#13](https://github.com/googlefonts/lang/pull/13/files))

Bringing this here so perhaps Nathan could confirm if 1 is possible in this case (as Rosa is asking) and if 2 is also required for languages included in 1.

**Comment by jvgaultney** [comment]
This is still not working properly.

**Comment by jvgaultney** [comment]
This remains a problem and seems to be getting no attention. This looks bad for both Google and SIL.

**Comment by chrissimpkins** [comment]
@jvgaultney We have these changes queued for the next data push.  Thanks for the prompt!

**Comment by RosaWagner** [comment]
All in prod now :)

**Comment by jvgaultney** [comment]
Thank you!
