### ISSUE TITLE
Language ≠ Script

### ISSUE THREAD

**Issue by tiroj** [googlefonts/lang#58]
The ‘Language’ dropdown menu contains an inconsistent mix of script and language identifiers. So, for example, ‘Bengali’ which could refer to either the Bengali* language or to the Bengali script, which is also used to write several other languages; ‘Devanagari’ on the other hand refers only to the script, which is used to write numerous languages that exhibit significant orthographic differences that may be reflected in font selection or OpenType Layout behaviour; such orthographic differences are explicitly recognised in the three types of Chinese identified in the list; and ‘Vietnamese’ appears to be the only entry in the ‘Language’ list that unambiguously refers to a language rather than a script.

I would like to suggest that Google Fonts consider moving to a system of two linked menus: one for script and one for language, with the content of the latter depending on the selection of the former. This would enable finer-grain browsing of fonts, and more accurate selection of results, especially if fonts contain a meta table that identifies primary design script or language tags, which could be taken into account in prioritising results. So, for example, almost all Devanagari fonts will support Hindi language reasonably well, but might be particularly tailored to the orthographic conventions of Marathi or Sanskrit (as is the case with fonts in the Tiro Indic collection). Even if fonts do not contain meta tables, it would be a good idea for Google Fonts to tag fonts in a way that prioritises browsing results by script and language, and this would also make it easier to improve specimen language selection. At the moment, for example, all Devanagari fonts show the same Hindi specimen texts, regardless of the orthography targets of the fonts.

* Bangla is the preferred endonym for both the language and script.

**Comment by simoncozens** [comment]
I just noticed that we now have two linked menus! Fantastic!

<img width="292" alt="Screenshot 2024-09-12 at 07 54 46" src="https://github.com/user-attachments/assets/199a8902-2651-4b88-ae5a-128f32d10ced">

I'll fix the Bangla issue.
