### ISSUE TITLE
Gunjala Gondi not showing despite primary script

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/lang#64]
Same issue as in #31 that was fixed in https://github.com/google/fonts/pull/5819/files
[Narnoor](https://github.com/google/fonts/pull/5988) in sandbox shows only Latin.

I was not here when the Mingzat got fixed, @chrissimpkins @tomasdev, is there anything needed to be done prior to adding languages in METADATA.pb?

**Comment by RosaWagner** [comment]
Same for primary_script: "Tfng". Shall I just do like in Noto and have the languages in addition to the primary script?

**Comment by RosaWagner** [comment]
sample text needs to be added to Gunjala Gondi language.

**Comment by simoncozens** [comment]
We do need sample text for Gunjala Gondi, but I'm not sure where we'll get it from. In the meantime you could add language `sa_Gong` which has sample text.

**Comment by simoncozens** [comment]
> I'm not sure where we'll get it from

Sounds like we should actually ask SIL for this.

**Comment by chrissimpkins** [comment]
@jvgaultney is this something your team might be able to help us with?  If not, do you happen to have any contacts who might?

**Comment by jvgaultney** [comment]
Yes - we can help you get Gunjala Gondi text. How much do you need? I'm about to go on three weeks leave, but @devosb may be able to help, as he has contacts in the extended community.

**Comment by simoncozens** [comment]
We would need a replacement for this:

```
name: "Sanskrit, Gunjala Gondi"
region: "IN"
sample_text {
  masthead_full: "𑶀𑵺𑶖"
  masthead_partial: "𑶇𑶋"
  styles: "𑵬𑵳𑶗𑶈 𑶀𑵶𑵳𑶋 𑶉𑶊𑵺𑶗𑵳𑶋𑵺𑶗𑵬𑶊𑵬𑶉𑶗𑵭𑶊𑵳𑵺𑶗𑵳𑶗𑶈𑶗𑵬𑶊𑵺𑶊𑶕 𑵡𑵹𑶊𑶈𑶖"
  tester: "𑶉𑶈𑶗𑵭𑶐 𑵰𑶊𑵺𑵭𑶊𑶖 𑶉𑶗𑵭𑵳𑵺𑶗𑵳𑶗𑶈𑶊𑶖 𑶉𑵰𑶍𑵳𑶗𑶅𑵺𑶗𑵺𑶊𑶖 𑵭𑶈𑶗𑵳𑵺𑶗𑵳𑶐 𑵠𑶅𑶋 𑵻, 𑵶𑶔𑶈𑵭𑵸𑶗𑶈𑶍𑶉𑶊"
  poster_sm: "𑵠𑶉𑶗𑵬𑶊𑶕 𑵠𑵯𑶋"
  poster_md: "𑵧𑵳𑵸𑵳𑶋𑶈𑶋𑵱𑶗𑵳𑵰,"
  poster_lg: "𑶉𑶈𑶗𑵭𑶐"
  specimen_48: "𑵺 𑵱𑵰𑶅𑶋 𑶀𑵺𑶕 𑵸𑶊𑶉𑵳𑶗𑵭𑶐𑵺 𑶅𑶈𑶊𑵹𑶌𑵺𑵳𑶗𑵭𑶐𑵺 𑵭𑶊 𑵹𑶊𑶈𑵬𑶋𑵳𑶍𑶕 𑵠𑵺𑶍𑶀𑶗𑵺𑶊𑶉𑶗𑵬𑵳𑶐. 𑵠𑶅𑶋"
  specimen_36: "𑵺 𑵱𑵰𑶅𑶋 𑶀𑵺𑶕 𑵭𑶋𑶈𑶍𑵹𑶗𑵬 𑵠𑵭𑵰𑶊𑵺𑵺𑶊𑵳𑶗𑵰𑵱𑶕 𑵭𑶗𑵬𑵭𑶇𑶊𑶈𑶕 𑵸𑵺𑶗𑶂𑶕 𑵭𑶊 𑵱𑶗𑶈𑶎𑶈𑶕 𑵠𑵰𑶊𑵺𑵭𑶌𑵬𑶕 𑶅𑶗𑶈𑵳𑶓𑵸𑵺𑶕 𑵭𑶊 𑶅𑶗𑶈𑵭𑶈𑶗𑵳𑵬𑶋𑵳𑶍𑶕 𑵠𑵺𑶍𑶀𑶗𑵺𑶊𑶉𑶗𑵬𑵳𑶐."
  specimen_32: "𑵭𑶋𑵹𑶋𑵺𑶊 𑶉𑶕𑵭𑶋𑵹𑶊𑵺𑶐𑵺 𑵭𑶊 𑶅𑶗𑶈𑵸𑵳𑶗𑵳𑶊𑵺𑶊𑶕 𑵰𑶔𑵵𑶋𑵱𑶊𑵹𑶋𑵱𑶊𑶈𑶊𑵺𑶊𑵰𑶍𑵵𑶗𑵵𑶕𑵷𑵺𑵱𑶊𑶈𑶗𑵬𑶊𑵺𑶊𑶕 𑵱𑶗𑶈𑶍𑵳𑶐, 𑵬𑶓𑵶𑶗𑵬𑶑𑶖 𑶈𑶊𑶉𑶗𑵽𑶗𑶈𑶋𑵬𑵺𑶗𑵬𑶊𑵬𑶅𑶌𑵾𑶑𑶖 𑶉𑶕𑶉𑶗𑵳𑶍𑵳𑶊𑵺𑶊𑶕 𑶅𑶗𑶈𑵯𑶊𑵭𑶋𑵺𑶊𑶕 𑶉𑵰𑶍𑶅𑶊𑵬𑶊𑵺𑶊𑶕 𑶅𑶗𑶈𑵬𑶓𑵶𑶊𑶈𑶗𑶇𑶓 𑶇𑶋 𑶉𑶈𑶗𑵭𑶓 𑶀𑵺𑶓𑶉𑶗𑵳𑶋."
  specimen_21: "𑵺 𑵱𑶓𑶅𑶋 𑶀𑵺𑶖 𑶉𑶗𑵭𑶐𑵻𑶗𑵼𑵬𑶊 𑵺𑶋𑵶𑶗𑶈𑶇𑶌𑵳𑶍𑶕, 𑵹𑶈𑶗𑵳𑶍𑶕, 𑵺𑶋𑶉𑶗𑵱𑶊𑶉𑵬𑶋𑵳𑶍𑶕 𑵭𑶊 𑵠𑵺𑶍𑶀𑶗𑵺𑶊𑶉𑶗𑵬𑵳𑶐.\n𑶉𑶈𑶗𑵭𑶓𑶅𑶋 𑶀𑵺𑶖, 𑶉𑶗𑵭𑶕 𑵭𑶋𑶈𑶍𑵹𑶗𑵬 𑶅𑶗𑶈𑵭𑶈𑶗𑵳𑶗𑵳𑶋𑵳𑶉𑶗𑵬 𑵱𑶉𑶗𑵬𑶊𑶅𑶋 𑵡𑶅𑶈𑶊𑵹𑶋𑵱𑶊𑵱𑶗𑶉𑶐𑶅𑶉𑶗𑵬, 𑶉𑶗𑵭𑶌𑵬𑶊𑵹𑶋𑵱𑶊𑶈𑶊𑵺𑶊𑶕 𑵸𑶊𑵬𑶋𑵳𑶗𑵭𑶊𑵺𑶊𑶕 𑵻, 𑵭𑶋𑵺𑶋𑶈𑶗𑵹𑶊𑶈𑵺𑶉𑶗𑵬 𑵻 𑵱𑶗𑶈𑶍𑵳𑶐, 𑶉𑶗𑵭𑶊𑵹𑶌𑵺𑶐𑵺 𑵺𑶋𑶉𑶗𑶅𑵱𑶗𑶉𑶐𑵺 𑵻 𑵺𑶗𑵬𑶊𑵬𑶅𑶌𑵾𑶐𑵺 𑵭𑶋𑵹𑶌𑵬𑵰𑶊𑵺𑶉𑶗𑵬 𑶉𑵰𑶍𑵻𑶋𑵳𑶉𑶗𑵬 𑶉𑶊𑶈𑶗𑵭𑶀𑵺𑶋𑵱𑶉𑶗𑵬 𑶉𑶗𑶈𑵭𑵺𑶉𑶗𑵬 𑵻 𑵱𑶗𑶈𑶍𑵳𑶐 𑶉𑶈𑶗𑵭𑶓𑶅𑶋 𑶀𑵺𑶖 𑶅𑶎𑶈𑶗𑵺𑶊𑶕 𑶉𑵰𑶊𑵺𑵳𑶊𑶕 𑵹𑶊𑶈𑵬𑵳𑶋."
  specimen_16: "𑵺 𑵱𑶉𑶗𑵬𑶊𑶅𑶋 𑵭𑶗𑵬𑵱𑶗𑵳𑶋𑵶𑵳𑶐 𑶅𑶊𑶈𑶋𑵭𑶊𑶈𑶋𑵱𑶐 𑵻 𑶀𑶌𑵭𑵺𑶐, 𑵶𑶗𑶈𑶍𑶇𑶐, 𑶅𑵳𑶗𑶈𑵭𑶗𑵬𑵭𑶇𑶊𑶈𑶐 𑵻 𑶉𑶗𑵭𑶐𑵻𑶗𑵼𑵬𑶊 𑶇𑶉𑶗𑵳𑵱𑶗𑶉𑶐𑶅𑶓𑵺𑶍𑶀𑶗𑵺𑶊𑶉𑶗𑵬𑵳𑶐, 𑵺 𑵭𑶊 𑵱𑶉𑶗𑵬𑶊𑶅𑶋 𑵲𑶗𑵬𑶊𑵳𑶋𑶕 𑶉𑵰𑶗𑵰𑶊𑵺𑶕 𑵭𑶊𑵱𑶗𑶈𑶊𑵺𑶗𑵳𑶍𑶕 𑵱𑶓𑶅𑶋 𑶉𑵱𑶗𑶉𑶗𑵬𑵳𑶋. 𑵧𑵳𑶊𑶇𑵱𑶇𑶉𑶗𑵳𑵱𑶗𑶉𑶐𑶅𑶊𑵱𑶗𑶈𑵰𑵺𑶊𑵺𑶋 𑵭𑶋𑶈𑶍𑵹𑶗𑵬 𑶅𑶗𑶈𑵳𑶗𑵬𑶐𑵱𑵰𑶅𑶋𑶀𑵺𑶖 𑵭𑶋𑵹𑶋𑶉𑶕𑶈𑵱𑶗𑶉𑵺𑶕 𑶉𑶕𑵹𑵳𑶗𑵳𑶐.\n𑶅𑶗𑶈𑵳𑶗𑵬𑶐𑵱𑵰𑶅𑶋 𑵭𑶋𑵻𑶊𑶈𑶊𑵺𑶊𑶕 𑵻𑶐𑵳𑵺𑶊𑵬𑶊𑶖 𑵹𑶈𑶗𑵰𑶉𑶗𑵬 𑵻𑶉𑶗𑵭𑶊𑵳𑵺𑶗𑵳𑶗𑶈𑶗𑵬𑶊𑵹𑶋𑵱𑶊𑶈𑶕 𑶉𑶕𑵹𑵳𑶗𑵳𑶐. 𑵠𑶉𑶗𑵰𑶋𑵺 𑵠𑵹𑶋𑵱𑶊𑶈𑶐, 𑶉𑶗𑵭𑶌𑵬𑶕 𑵹𑶈𑶗𑵰𑶕 𑵭𑶋𑶉𑶗𑵭𑶊𑶉𑶕 𑵭𑶊 𑶉𑶋𑵱𑶗𑶉𑵬𑶋𑵳𑶍𑶕 𑵠𑵯𑶗𑵬𑶉𑶗𑵳𑶍𑶕 𑵠𑶈𑶗𑵻𑶋𑵳𑶍𑶕 𑶅𑶈𑶋𑶅𑶊𑵵𑵬𑶋𑵳𑶍𑶕 𑵭𑶊, 𑵭𑶑𑵬𑵱𑶗𑵳𑶋𑵱𑶐 𑶉𑶊𑵰𑶊𑶀𑶋𑵱𑶐 𑵻 𑶀𑶌𑵭𑵺𑶐, 𑵠𑵺𑶗𑵬𑶑𑶉𑶗𑵻 𑶉𑶇 𑶉𑶊𑵰𑶍𑵸𑶊𑵬𑶋𑵱𑶀𑶌𑵭𑵺𑶐 𑵧𑵱𑶊𑵱𑶋𑵺𑶊 𑵭𑶊 𑶉𑶗𑵭𑶌𑵬𑶕 𑵹𑶈𑶗𑵰𑶕 𑵭𑶋𑶉𑶗𑵭𑶊𑶉𑶕𑶉𑶗𑵭𑶊𑵳𑵺𑶗𑵳𑶗𑶈𑶗𑵬𑶕 𑵻 𑶅𑶈𑶋𑵭𑶈𑶗𑵳𑵬𑶋𑵳𑶍𑵰𑶅𑶋 𑶅𑶗𑶈𑵳𑶗𑵬𑶐𑵱𑶕 𑶀𑵺𑶖 𑶉𑶗𑵭𑶊𑵳𑵺𑶗𑵳𑶗𑶈𑶗𑵬𑶕 𑵹𑶊𑶈𑵬𑵳𑶋.\n𑶅𑶗𑶈𑵳𑶗𑵬𑶐𑵱𑵰𑶅𑶋 𑵰𑵺𑶗𑵳𑵭𑶗𑵬𑶊𑵯𑶋𑵭𑶗𑵬𑵱𑶗𑵳𑶗𑵬𑶓𑶖 𑵠𑵹𑶋𑵱𑶊𑶈𑶕 𑶉𑶕𑵹𑵳𑶗𑵳𑶐. 𑶉𑶌𑵰𑶊𑵭𑶗𑵬𑵭𑵹𑶊𑵺𑶕 𑵠𑵭𑶋𑵶𑵺𑵬𑶗𑵬, 𑵱𑶐𑵺𑶊𑶅𑶋 𑶉𑶕𑵻𑶊𑶈𑵰𑶊𑵹𑶗𑵬𑵰𑶐𑵺 𑵭𑶋𑵻𑶊𑶈𑶊𑵺𑶊𑶕 𑶉𑶎𑵻𑵺𑶊𑵺𑶊𑶕 𑵻 𑵡𑵸𑶊𑵺𑶅𑶗𑶈𑵸𑶊𑵺𑶊𑶈𑶗𑵴𑶕 𑵭𑶋𑵺𑶑𑵭 𑶇𑶉𑶗𑵳𑵱𑶗𑶉𑶐𑶅𑶕 𑵱𑶋𑶉𑶗𑵻𑵸𑶅𑶋 𑶀𑵺𑶖, 𑶉𑶗𑵭𑶌𑵬𑵰𑵺𑶗𑵳𑵭𑶗𑵬𑶉𑶕𑵷𑶊𑶈𑵺𑶊𑶈𑶗𑵴𑶕 𑵠𑵹𑶋𑵱𑶊𑶈𑶐𑶉𑶗𑵰𑶋𑵺 𑵠𑶈𑶗𑶇𑶋𑶉𑶗𑵬𑵳𑶐."
}
```

So:

* `masthead_full`: One word
* `masthead_partial`: A letter or two
* `styles`: A few words
* `tester`: A sentence
* `poster_sm`/`poster_md`/`poster_lg`: A few words

and then various snippets of a paragraph. It should be "neutral" text (non religious/political). We normally use translations of UDHR, or something related to the concept of writing.

**Comment by devosb** [comment]
Working with @markpenny I produced
[wsg_Gong.txt](https://github.com/googlefonts/lang/files/11436374/wsg_Gong.txt) Will this work?

**Comment by jvgaultney** [comment]
This does not seem to be live yet, and holding up the availability of Narnoor.

**Comment by simoncozens** [comment]
The sample text above *is* live in the system; I can see it from the Noto Sans Gunjala Gondi page (although the masthead text has got corrupted somehow.) As the labels on the Narnoor PR show, Narnoor is currently in sandbox and will move from there to production if there are no problems.
