### ISSUE TITLE
Regenerate pb2 files

### ISSUE THREAD

**Issue by meerfrau** [googlefonts/lang#94]
Preface: It is perfectly possible to run with the help of `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python diffenator`

How may I regenerate the Protobuf files with a newer protoc compiler?

I know that protobuf is pinned https://github.com/googlefonts/lang/pull/19 – I'm just asking how to fix my own issue without changing your source tree.

**Comment by moyogo** [comment]
@meerfrau I use protoc from protobuf 3.16 to minimize the differences.
